#!/bin/bash

# AWS Deployment Script for Exercise Timer App
# This script deploys the app using AWS Free Tier services

set -e

echo "🚀 Deploying Exercise Timer App to AWS..."

# Check if AWS CLI is installed
if ! command -v aws &> /dev/null; then
    echo "❌ AWS CLI is not installed. Please install it first:"
    echo "   https://aws.amazon.com/cli/"
    exit 1
fi

# Check if SAM CLI is installed
if ! command -v sam &> /dev/null; then
    echo "❌ AWS SAM CLI is not installed. Installing..."
    echo "   Install from: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html"
    exit 1
fi

# Check AWS credentials
if ! aws sts get-caller-identity &> /dev/null; then
    echo "❌ AWS credentials not configured. Run: aws configure"
    exit 1
fi

STAGE=${1:-dev}
REGION=${AWS_REGION:-us-east-1}

echo "📦 Stage: $STAGE"
echo "🌍 Region: $REGION"

# Install Lambda dependencies
echo "📥 Installing Lambda dependencies..."
cd "$(dirname "$0")"
npm install --production --prefix . 2>/dev/null || npm install --production

# Build and deploy with SAM
echo "🏗️  Building SAM application..."
sam build

echo "🚀 Deploying to AWS..."
sam deploy \
  --stack-name exercise-timer-$STAGE \
  --region $REGION \
  --capabilities CAPABILITY_IAM \
  --parameter-overrides Stage=$STAGE \
  --no-confirm-changeset \
  --no-fail-on-empty-changeset

# Get API endpoint and Cognito config
echo "📡 Getting API endpoint and Cognito configuration..."
API_URL=$(aws cloudformation describe-stacks \
  --stack-name exercise-timer-$STAGE \
  --region $REGION \
  --query 'Stacks[0].Outputs[?OutputKey==`ApiUrl`].OutputValue' \
  --output text)

USER_POOL_ID=$(aws cloudformation describe-stacks \
  --stack-name exercise-timer-$STAGE \
  --region $REGION \
  --query 'Stacks[0].Outputs[?OutputKey==`UserPoolId`].OutputValue' \
  --output text)

CLIENT_ID=$(aws cloudformation describe-stacks \
  --stack-name exercise-timer-$STAGE \
  --region $REGION \
  --query 'Stacks[0].Outputs[?OutputKey==`UserPoolClientId`].OutputValue' \
  --output text)

IDENTITY_POOL_ID=$(aws cloudformation describe-stacks \
  --stack-name exercise-timer-$STAGE \
  --region $REGION \
  --query 'Stacks[0].Outputs[?OutputKey==`IdentityPoolId`].OutputValue' \
  --output text)

# Update config.js with Cognito values and API URL
echo "📝 Updating Cognito configuration..."
cat > public/config.js << EOF
// Cognito Configuration - Auto-generated by deploy script
window.COGNITO_USER_POOL_ID = '$USER_POOL_ID';
window.COGNITO_CLIENT_ID = '$CLIENT_ID';
window.COGNITO_REGION = '$REGION';
window.COGNITO_IDENTITY_POOL_ID = '$IDENTITY_POOL_ID';
window.API_GATEWAY_URL = '$API_URL';
EOF

echo ""
echo "✅ Deployment complete!"
echo ""
echo "📡 API URL: $API_URL"
echo "🔐 User Pool ID: $USER_POOL_ID"
echo "🔑 Client ID: $CLIENT_ID"
echo ""
echo "📝 Next steps:"
echo "   1. Update public/app.js to use API URL: $API_URL"
echo "   2. Deploy frontend to S3 (see deploy-frontend.sh)"
echo "   3. Cognito config has been updated in public/config.js"
echo ""
echo "💰 Cost Protection:"
echo "   - API Gateway: 10 requests/second max (free tier: 1M/month)"
echo "   - Lambda: 128MB memory, 10s timeout (free tier: 1M requests/month)"
echo "   - S3: Free tier includes 5GB storage"
echo "   - Cognito: Free tier includes 50,000 MAU (Monthly Active Users)"
echo ""



